import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Kanban",
  description: "Generated by create next app",
};

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

type LayoutProps = {
  session: Session;
} & PropsWithChildren;

const RootLayout = ({ session, children }: LayoutProps) => {
  return (
    <html lang="fr">
      <SessionProvider session={session}>
        <body className={jakarta.className}>{children}</body>
      </SessionProvider>
    </html>
  );
};

export default RootLayout;
